version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST:-kafka}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_PORT: 9092
      HOSTNAME_COMMAND: ${HOST:-kafka}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_NUM_PARTITIONS: ${PARTITIONS_PER_TOPIC:-3}
    links:
      - zookeeper
  node_1:
      build: .
      ports:
        - "8080:8080"
      environment:
        KAFKA_MBR: "${HOST:-kafka}:9094"   
        WSS_PORT: ${WSS_PORT:-8080}
      volumes:
        - ${CONF_PATH:-$(pwd)/test/configs/}:/usr/src/app/conf:ro
      links:
        - kafka
  node_2:
        build: .
        ports:
          - "8081:8081"
        environment:
          KAFKA_MBR: "${HOST:-kafka}:9094"       
          WSS_PORT: ${WSS_PORT:-8081}
        volumes:
          - ${CONF_PATH:-$(pwd)/test/configs/}:/usr/src/app/conf:ro
        links:
          - kafka
  node_3:
          build: .
          ports:
            - "8082:8082"
          environment:
            KAFKA_MBR: "${HOST:-kafka}:9094"
            WSS_PORT: ${WSS_PORT:-8082}
          volumes:
            - ${CONF_PATH:-$(pwd)/test/configs/}:/usr/src/app/conf:ro
          links:
            - kafka
